# Create a NumPy ndarray

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [11]:
import numpy as np

arr_1d =np.array([1,2,3,4,5,6])
arr_1d


array([1, 2, 3, 4, 5, 6])

In [13]:
arr_2d =np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [15]:
arr_0d = np.array(10)
print(arr_0d)

10


In [14]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]]


# Check Number of Dimensions


In [16]:
arr_1d.ndim

1

In [17]:
arr_2d.ndim

2

In [18]:
arr_3d.ndim

3

# NumPy Array Indexing

In [20]:
arr_1d[2]

3

In [24]:
arr_2d =np.array([[1, 2, 3], [4, 5, 6]])
arr_2d[1]

array([4, 5, 6])

# NumPy Array Slicing

## define the step, like this: [start:end:step]

In [25]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7])
arr_1d[0:4]

array([1, 2, 3, 4])

In [26]:
arr_1d[1:5:2]

array([2, 4])

### Slicing 2-D Arrays

In [27]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr_2d[0,1:4]

array([2, 3, 4])

In [28]:
arr_2d[1,1:4]

array([7, 8, 9])

### Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [30]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr_2d.size

10

In [31]:
arr_2d.shape

(2, 5)

In [32]:
arr_2d.dtype

dtype('int32')

### Creating  matrix 

### 1) np.ones() Python NumPy Function
### 2) np.zeros() Python NumPy Function
### 3) np.empty() Python NumPy Function

In [36]:
arry_1 = np.ones((3,5),dtype=int)
arry_1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
arry_1 = np.ones((3,5),dtype=bool)
arry_1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [38]:
arry_2 = np.zeros((3,5),dtype=bool)
arry_2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [45]:
arry_2 = np.zeros((3,5),dtype= float)
arry_2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Numpy functions

#### 1) np.arange() Python NumPy Function
#### 2) np.linspace() Python NumPy Function
#### 3) np.reshape() Python NumPy Function
#### 4) np.ravel() Python NumPy Function
#### 5) np.flatten() Python NumPy Function
#### 6) np.transpose() Python NumPy Function


In [50]:
np.arange(1,10,2,dtype=float) 

array([1., 3., 5., 7., 9.])

In [57]:
np.linspace(1,5,8,dtype=int)

array([1, 1, 2, 2, 3, 3, 4, 5])

In [70]:
arr =np.array([1,2,3,4,5,6,7,8])

In [73]:
arr_2d = arr.reshape(2,4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
arr_3d = arr.reshape(2,4)
arr_3d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
arr_3d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
arr_2d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
arr_3d.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# matrix computation

In [95]:
arr_1 = np.arange(1,10,dtype=int).reshape(3,3)
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
arr_2 = np.arange(10,19,dtype=int).reshape(3,3)
arr_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [96]:
np.add(arr_1,arr_2)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [97]:
np.subtract(arr_1,arr_2)

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [98]:
np.divide(arr_1,arr_2)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [99]:
np.multiply(arr_1,arr_2)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [100]:
arr_1 @ arr_2  #matrix row column multiplication first row first coloumn

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [101]:
arr_1.dot(arr_2) #this also matrix row column multiplication first row first coloumn

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

#### max , argmax, axis=0(for col),axis=1(for row), mean,sum,std(stanndard deviation)
#### log, exp

In [112]:
arr = np.arange(1,10,dtype=int).reshape(3,3)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
arr.max(axis=0) #which is bigger is column 

array([7, 8, 9])

In [118]:
arr.max()

9

In [108]:
arr.argmax()  #Returns the indices of the maximum values along an axis

8

In [120]:
np.std(arr)

2.581988897471611

In [121]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [123]:
np.log10(arr)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [124]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# Slicing in numpy

In [128]:
b_array = np.arange(1,101).reshape(10,10)
print(b_array)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [130]:
b_array[1:5]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [146]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,0:1 ])


[[1]
 [6]]


In [138]:
print(arr[0:2, 2 ])

[3 8]


In [144]:
b_array[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

# vstack and hstack and split

In [150]:
arr1 = np.arange(1,10).reshape(3,3) 
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
arr2 = np.arange(11,20).reshape(3,3) 
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [154]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [157]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3, 11, 12, 13,  1,  2,  3],
       [ 4,  5,  6, 14, 15, 16,  4,  5,  6],
       [ 7,  8,  9, 17, 18, 19,  7,  8,  9]])

# trigonometry functions

In [160]:
b_array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [161]:
np.tan(b_array)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01, -6.79971146e+00, -4.52315659e-01,
         6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
         3.49391565e+00, -1.13731371e+00,  1.51589471e-01,
         2.23716094e+00],
       [-1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
        -2.13489670e+00, -1.33526407e-01,  1.17875355e+00,
        -3.27370380e+00, -2.81429605e-01,  8.87142844e-01,
        -6.40533120e+00],
       [-4.41695568e-01,  6.61006041e-01, -7.53130148e+01,
        -6.23498963e-01,  4.73814720e-01,  7.75047091e+00,
        -8.40771255e-01,  3.10309661e-01,  3.61455441e+00,
        -1.11721493e+00],
       [ 1.60656699e-01,  2.29138799e+00, -1.49838734e+00,
         1.77046993e-02,  1.61977519e+00, -2.08661353e+00,
        -1.24527568e-01,  1.20012724e+00, -3.17290855e+00,
        -2.

In [164]:
np.sin(b_array*np.pi)

array([[ 1.22464680e-16, -2.44929360e-16,  3.67394040e-16,
        -4.89858720e-16,  6.12323400e-16, -7.34788079e-16,
         8.57252759e-16, -9.79717439e-16,  1.10218212e-15,
        -1.22464680e-15],
       [ 4.89982516e-15, -1.46957616e-15, -1.96067284e-15,
        -1.71450552e-15,  5.38968388e-15, -1.95943488e-15,
        -1.47081412e-15, -2.20436424e-15,  5.87954260e-15,
        -2.44929360e-15],
       [-9.80955401e-16, -9.79965032e-15,  6.36940132e-15,
        -2.93915232e-15, -4.91096681e-16,  3.92134568e-15,
         6.85926004e-15, -3.42901104e-15, -1.23796127e-18,
        -1.07793678e-14],
       [ 7.34911876e-15, -3.91886976e-15,  4.88620758e-16,
         2.94162824e-15,  7.83897748e-15, -4.40872848e-15,
         9.78479478e-16, -1.17590852e-14,  8.32883620e-15,
        -4.89858720e-15],
       [ 1.56791929e-14,  1.96191080e-15,  8.81869492e-15,
        -1.95993006e-14,  1.95819692e-15, -1.27388026e-14,
        -4.90230108e-15, -5.87830464e-15,  1.66589104e-14,
         9.

# Rnadom sampling in numpy

In [165]:
import random
import numpy as np

In [171]:
np.random.random((3,3))

array([[0.9467866 , 0.29692474, 0.37308853],
       [0.44077464, 0.8906526 , 0.72052758],
       [0.46563063, 0.38033089, 0.34509432]])

In [172]:
np.random.randint(1,4)

3

In [175]:
np.random.randint(1,4,(4,4))

array([[3, 3, 1, 2],
       [1, 1, 3, 1],
       [1, 1, 1, 1],
       [3, 1, 2, 1]])

In [177]:
np.random.randint(1,4,(4,4,2))

array([[[2, 2],
        [3, 2],
        [3, 3],
        [3, 2]],

       [[2, 2],
        [2, 2],
        [3, 3],
        [1, 3]],

       [[2, 2],
        [1, 2],
        [2, 3],
        [3, 3]],

       [[2, 1],
        [3, 2],
        [3, 2],
        [2, 3]]])

In [179]:
np.random.rand(3,3)

array([[0.95732836, 0.8795087 , 0.18330473],
       [0.91488852, 0.01623365, 0.13669905],
       [0.20350751, 0.83215599, 0.57290205]])

# String operation in numpy, comparison and information

In [184]:
name1 = "my name is"
name2 = "sambhav kumar gupta"

In [182]:
np.char.add(name1,name2)

array('my name issambhav kumar gupta', dtype='<U29')

In [185]:
np.char.lower(name1)

array('my name is', dtype='<U10')

In [186]:
np.char.upper(name1)

array('MY NAME IS', dtype='<U10')

In [187]:
np.char.center(name1,60)

array('                         my name is                         ',
      dtype='<U60')

In [188]:
np.char.center(name1,60, fillchar="*")

array('*************************my name is*************************',
      dtype='<U60')

In [189]:
np.char.split(name1)

array(list(['my', 'name', 'is']), dtype=object)

In [190]:
np.char.splitlines("my name is\nsambhav")


array(list(['my name is', 'sambhav']), dtype=object)

In [196]:
str1 = 'dmy'
str2 = 'dmy'
np.char.join([":","/"],[str1,str2])

array(['d:m:y', 'd/m/y'], dtype='<U5')

In [197]:
np.char.replace(name1,"is","are")

array('my name are', dtype='<U11')

In [199]:
np.char.find(str1,'is')

array(-1)